
- name: "[Firewall] Configure additional firewall features"
  hosts: firewall
  become: true
  gather_facts: true
  any_errors_fatal: true

  roles:
    - role: promtail
    - role: arillso.logrotate
    # - role: linux-system-roles.nbde_server
    # - role: geerlingguy.node_exporter
    # - role: keepalived
    # - role: haproxy
