---
- name: "Host Adoption playbook"
  hosts: "{{ target_hosts | default('none') }}"
  gather_facts: true
  become: true
  tasks:

    - name: General config and users
      ansible.builtin.include_role:
        name: misc

    - name: Configures SSHd and deploys certificate trust
      ansible.builtin.include_role:
        name: sshd

    - name: Deploy local certificate authority
      ansible.builtin.include_role:
        name: certenroll
