---
- name: NAS + KMS Provisioning
  hosts: "{{ target_hosts | default('storage') }}"
  become: true
  gather_facts: true
  any_errors_fatal: true
  tasks:

    - name: Configure Certificates
      ansible.builtin.include_role:
        name: certenroll

    - name: Install OpenBao
      ansible.builtin.include_role:
        name: openbao

    - name: Install and configure NFS
      block:
        - name: Install NFSd
          ansible.builtin.include_role:
            name: geerlingguy.nfs

        - name: Open firewall port for NFSd
          ansible.posix.firewalld:
            immediate: true
            permanent: true
            state: enabled
            service: nfs

    - name: Install RustFS
      ansible.builtin.include_role:
        name: rustfs


# TODO
# - Set up ssh disk unlocking?
