---
- name: Set system timezone
  community.general.timezone:
    name: "{{ misc_system_timezone }}"

- name: Enable EPEL repository
  ansible.builtin.dnf:
    name: epel-release
    state: present
    update_cache: true

- name: Install requested packages
  ansible.builtin.dnf:
    name: "{{ misc_system_packages }}"
    state: present
    update_cache: true

- name: Download and install binaries from sources
  with_items: "{{ misc_binaries }}"
  ansible.builtin.unarchive:
    src: "{{ item.src_url }}"
    dest: "{{ misc_bin_pfx }}"
    creates: "{{ misc_bin_pfx }}/{{ item.name }}"
    include: "{{ item.include | default(omit) }}"
    extra_opts: "{{ item.extra_opts | default(omit) }}"
    remote_src: true
    mode: "u+rx,g+rx,o+rx"
    owner: root
    group: root

- name: Network Configuration | Set hostname to inventory hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Network Configuration | Update hosts
  ansible.builtin.copy:
    dest: /etc/hosts
    content: |
      127.0.1.1 {{ inventory_hostname }} localhost
      ::1 {{ inventory_hostname }} localhost ip6-localhost ip6-loopback
      ff02::1 ip6-allnodes
      ff02::2 ip6-allrouters
    mode: preserve

- name: System Configuration | Tune sysctls
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/100-ansible-misc.conf
    reload: true
  with_dict: "{{ misc_sysctl_config }}"

- name: Allow designated users to sudo without password
  ansible.builtin.copy:
    content: |
      #{{ item }}    ALL=(ALL)   NOPASSWD: ALL
      {{ item }} ALL=(ALL:ALL) NOPASSWD:SETENV: ALL
    dest: "/etc/sudoers.d/{{ item }}-nopasswd"
    owner: root
    group: root
    mode: "0440"
  with_items: "{{ misc_allow_sudo_nopasswd }}"
