---
- name: Ensure desired packages are installed
  ansible.builtin.include_tasks: packages.yml

- name: Configure user accounts and authentication
  ansible.builtin.include_tasks: auth.yml

- name: Configure system settings
  ansible.builtin.include_tasks: config.system.yml

- name: Configure user dotfiles and shell environment
  ansible.builtin.include_tasks: config.users.yml
