certenroll:
    cert: |
        -----BEGIN CERTIFICATE-----
        MIIDRzCCAsygAwIBAgIUAavPBHSO12tcICI+fh1BnwUs9jkwCgYIKoZIzj0EAwMw
        eTEmMCQGA1UECgwdWnludGhvdmlhbiBJbnRlcnN0ZWxsYXIgVW5pb24xKDAmBgNV
        BAsMH0RpZ2l0YWwgSW5mcmFzdHJ1Y3R1cmUgU2VydmljZXMxJTAjBgNVBAMMHFJv
        b3QgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkwHhcNMjYwNzAzMDMzMDU2WhcNMzYw
        NzAyMDMzMDU2WjBxMSYwJAYDVQQKDB1aeW50aG92aWFuIEludGVyc3RlbGxhciBV
        bmlvbjEoMCYGA1UECwwfRGlnaXRhbCBJbmZyYXN0cnVjdHVyZSBTZXJ2aWNlczEd
        MBsGA1UEAwwUeGVuaWEuenludGhvdmlhbi54eXowdjAQBgcqhkjOPQIBBgUrgQQA
        IgNiAATxEf+C92Mb20GyHAsphA+lfVl7xJ0RHpZTOL5JNQEaJcyTkyjCPAAY1z2w
        CaOMxC0uwkYFhQU1VpXjk7CVjmCpBUA7608PDH8XcfzWGAz2ZKtTFBStk1g+s7cX
        aJPN8sujggEbMIIBFzAJBgNVHRMEAjAAMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggr
        BgEFBQcDAjAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0OBBYEFEjD7CvCNc5x4W352cJs
        tMykNvHcMB8GA1UdIwQYMBaAFPMsFRHBm/ls92pIDVy8pofYLuO+MEEGCCsGAQUF
        BwEBBDUwMzAxBggrBgEFBQcwAoYlaHR0cDovL3BraS56eW50aG92aWFuLnh5ei9y
        b290LWNhLmNlcjA2BgNVHR8ELzAtMCugKaAnhiVodHRwOi8vcGtpLnp5bnRob3Zp
        YW4ueHl6L3Jvb3QtY2EuY3JsMCAGA1UdEQQZMBeCFXhlbmlhLnp5bnRob3ZpYW4u
        eHl6CjAKBggqhkjOPQQDAwNpADBmAjEAzNFjnXwP7p3G2yPlqpyUScrCACYvx3pY
        3jJHg4ra3fMAKsslhRxwEuJUCIBpYH+UAjEAmn0NoDZmTe3o1RGJnrd10isPCKF6
        rm680FnEf+DTARMkQq8frwwbYo3TUloKA8/W
        -----END CERTIFICATE-----
